name: CI

on:
  push:
    branches: [ "jenkinsdocker" ]
  pull_request:
    branches: [ "jenkinsdocker" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t demo-flask:latest .

      - name: Test
        run: docker run --rm demo-flask:latest python -c "import flask; print('OK')"
